name: CI

on:
  pull_request:
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  jest-test:
    uses: ./.github/workflows/jest-test.yaml
    
  create-timestamp:
    uses: ./.github/workflows/create-timestamp.yaml
    
  create-cache-key:
    uses: ./.github/workflows/create-cache-key.yaml
    
  build:
    strategy:
      matrix:
        arch: [ x86_64 ]
    uses: ./.github/workflows/build.yaml
    needs: create-cache-key
    with:
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
      arch: ${{ matrix.arch }}
  
  e2e-test:
    uses: ./.github/workflows/e2e-test.yaml
    needs: [ create-cache-key, build ]
    if: ${{ ! cancelled() }}
    with:
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
